version: "3.8"

services:
  mysql-standalone:
    container_name: mysql-standalone
    image: mysql:8.0
    build: .
    ports:
      - 13306:3306
    networks:
      - cheatsheet_network
    environment:
      MYSQL_DATABASE: CHEATSHEET
      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - mysql-db:/var/lib/mysql
    cap_add:
      - SYS_NICE

  cheatsheet:
    container_name: cheatsheet
    restart: on-failure
    image: rajapars/cheatsheet:0.0.1
    ports:
      - 8182:8182
    depends_on:
      - mysql-standalone
    command: ["-c", "wait-for.sh mysql-standalone:13306 && java -Dspring.profiles.active=docker cheatsheet.jar"]
    networks:
      - cheatsheet_network

  authentication:
    container_name: authentication
    image: rajapars/authentication:0.0.1
    restart: on-failure
    ports:
      - 8183:8183
    depends_on:
      - cheatsheet
    networks:
      - cheatsheet_network

networks:
  cheatsheet_network:
    name: cheatsheet_network

#volumes:
#  mysql-db:
#    name: mysql-db